# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7ca33d3ef848b43ed55ec0a9ed64d336112ea75cc9e55d7df449fd338d219adfa01a9d737d4685f5d6dee38fe14a0b2af8adc877843dbe333e3d9b72124dd4d

test:
  secret_key_base: 54af7fa349dc18ae56cd362c9dc416a48600af63b2a5e22e850e8e31932ee4104c1d63d65e59763a085868831b8eeed883606e36abec0e92b1612eace9b43c27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
